// <auto-generated />
using System;
using HotelverwaltungAPI.Models.db;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HotelverwaltungAPI.Migrations
{
    [DbContext(typeof(DbContextHotel))]
    partial class DbContextHotelModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.13");

            modelBuilder.Entity("BillRoom", b =>
                {
                    b.Property<int>("BillsBillID")
                        .HasColumnType("int");

                    b.Property<int>("RoomsRoomId")
                        .HasColumnType("int");

                    b.HasKey("BillsBillID", "RoomsRoomId");

                    b.HasIndex("RoomsRoomId");

                    b.ToTable("BillRoom");
                });

            modelBuilder.Entity("HotelverwaltungAPI.Models.Bill", b =>
                {
                    b.Property<int>("BillID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("GuestID")
                        .HasColumnType("int");

                    b.Property<bool>("Payed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("PaymentMethod")
                        .HasColumnType("text");

                    b.Property<DateTime>("PaymentTarget")
                        .HasColumnType("datetime");

                    b.HasKey("BillID");

                    b.ToTable("Bills");
                });

            modelBuilder.Entity("HotelverwaltungAPI.Models.Guest", b =>
                {
                    b.Property<int>("GuestID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("Birthdate")
                        .HasColumnType("datetime");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("Firstname")
                        .HasColumnType("text");

                    b.Property<string>("Language")
                        .HasColumnType("text");

                    b.Property<string>("Lastname")
                        .HasColumnType("text");

                    b.HasKey("GuestID");

                    b.ToTable("Guests");
                });

            modelBuilder.Entity("HotelverwaltungAPI.Models.Room", b =>
                {
                    b.Property<int>("RoomId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CountBeds")
                        .HasColumnType("int");

                    b.Property<bool>("HasBalcony")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("HasKitchen")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("HasTerrac")
                        .HasColumnType("tinyint(1)");

                    b.Property<decimal>("NightlyPrice")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("RoomId");

                    b.ToTable("Rooms");
                });

            modelBuilder.Entity("HotelverwaltungAPI.Models.RoomBill", b =>
                {
                    b.Property<int>("RoomId")
                        .HasColumnType("int");

                    b.Property<int>("BillId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime");

                    b.Property<int>("RoomDiscount")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime");

                    b.HasKey("RoomId", "BillId");

                    b.HasIndex("BillId");

                    b.ToTable("RoomsBills");
                });

            modelBuilder.Entity("BillRoom", b =>
                {
                    b.HasOne("HotelverwaltungAPI.Models.Bill", null)
                        .WithMany()
                        .HasForeignKey("BillsBillID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HotelverwaltungAPI.Models.Room", null)
                        .WithMany()
                        .HasForeignKey("RoomsRoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HotelverwaltungAPI.Models.RoomBill", b =>
                {
                    b.HasOne("HotelverwaltungAPI.Models.Bill", "Bill")
                        .WithMany("RoomBill")
                        .HasForeignKey("BillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HotelverwaltungAPI.Models.Room", "Room")
                        .WithMany("RoomBill")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bill");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("HotelverwaltungAPI.Models.Bill", b =>
                {
                    b.Navigation("RoomBill");
                });

            modelBuilder.Entity("HotelverwaltungAPI.Models.Room", b =>
                {
                    b.Navigation("RoomBill");
                });
#pragma warning restore 612, 618
        }
    }
}
